### ISSUE TITLE
Search boxes

### ISSUE THREAD

**Issue by derwin12** [derwin12/mywebscrape#40]
Perhaps JUST the box in the upper right?

Do we need the middle and far right one?

**Comment by MrPaulAR** [comment]
Agreed.  The navbar at the top sample I grabbed from the bootstrap site had that included so I made it functional.  Only left the one in the middle of the page there since that was close to what you had prior.

I'm fine with either of them being removed.  

Remove this from layouts.html for the top
`        <form class="d-flex" action="{{url_for('sequence')}}" method="post">
            <input class="form-control me-2" name="search_string" type="text" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
        </form>`

Or remove this from sequence.html for the one in the middle of the page.
`    <div class="container text-center col-3">
        <form class="search" action="{{url_for('sequence')}}" method="post">
            <input class="form-control me-2" name="search_string" type="text" placeholder="Search by store or sequence" value="{{request.form.sequence}}">
            <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
    </div>`

**Comment by derwin12** [comment]
Let's the remove the center one to start.

**Comment by MrPaulAR** [comment]
Removed middle search via 4ecd9e1bc8434bb1b83d9796837e17a58c0e8663
